### ISSUE TITLE
More control over positioning

### ISSUE THREAD

**Issue by izaxon** [accelerande/teldutala.fo#11]
We’d like to have ﬁner control over the positioning of the reading. We’d like the user to be able to pick from where you should start reading with the mouse cursor. So the user should be able to press a word, and have some indication that you have selected that word (e.g. highlighting the word), and when pressing play you would start reading from that word. It should not start reading from the entire paragraph, even though it might sound diﬀerent without the context, but the extra control is important.
In addition to this, for accessibility reasons, there should be a button to go back one sentence, so a blind person using accessibility software can go one sentence back without using the cursor.

**Comment by izaxon** [comment]
Double-click on word will start reading from that word? Or just mark the position at the word?

**Comment by izaxon** [comment]
This issues could be a bit time consuming, since it is tricky to get marking etc. working in all browsers.

**Comment by izaxon** [comment]
We have several alternatives:

a) double-click to start reading
b) possibility to read only selected text
c) possilibity to use navigation buttons (next/prev sentence and/or paragraph), as used by DAISY applications

**Comment by PaoloLeva** [comment]
From Bjartur: We think the double-click to read from the clicked position is a good feature, and we'd like to focus on that

**Comment by PaoloLeva** [comment]
To Bjartur: Just be aware that double-click to read from the clicked position is a feature that will not be accessible to visually impaired. This is why systems dedicated to visually impaired (like DAISY reader) prefer navigation buttons, often giving possibility to skip back/forth one sentence or one paragraph.
We will mention both possibilities (double-click and navigation) in the offer and then it will be up to you to choose.
