### ISSUE TITLE
Finer highlighting

### ISSUE THREAD

**Issue by izaxon** [accelerande/teldutala.fo#12]
The highlighting is as we have talked about before, with the option for wordfor-word highlighting similar to ReadSpeaker’s highlighting. Highlighting the entire sentence is a good feature, so having a darker highlighting color for the words while also highlighting the sentence would be a desired feature.

**Comment by izaxon** [comment]
![image](https://cloud.githubusercontent.com/assets/805898/20036614/bf4e11e8-a40c-11e6-903b-f4a6452b1ea6.png)

**Comment by izaxon** [comment]
Word for word highlighting is ok. It doesn't require a lot of work.

**Comment by izaxon** [comment]
Fixed in app.
To do on website...

**Comment by PaoloLeva** [comment]
It seems like our audio player does not perform good enough for highlighting words.

Here is what happens:

Text: "A terror suspect in Australia tried to smuggle a bomb."

Some word is skipped (or flickering) by the highlight. 

Logging from console:

50,21,22 => soundManager.onPosition('sound_0', 50, function () { setSubtitle(0,1); })
voiceportal.js:307 224,23,29 => soundManager.onPosition('sound_0', 224, function () { setSubtitle(2,8); })
voiceportal.js:307 561,30,37 => soundManager.onPosition('sound_0', 561, function () { setSubtitle(9,16); })
voiceportal.js:307 1139,38,40 => soundManager.onPosition('sound_0', 1139, function () { setSubtitle(17,19); })
voiceportal.js:307 1210,41,50 => soundManager.onPosition('sound_0', 1210, function () { setSubtitle(20,29); })
voiceportal.js:307 1788,51,56 => soundManager.onPosition('sound_0', 1788, function () { setSubtitle(30,35); })
voiceportal.js:307 2149,57,59 => soundManager.onPosition('sound_0', 2149, function () { setSubtitle(36,38); })
voiceportal.js:307 2296,60,67 => soundManager.onPosition('sound_0', 2296, function () { setSubtitle(39,46); })
voiceportal.js:307 2721,68,69 => soundManager.onPosition('sound_0', 2721, function () { setSubtitle(47,48); })
voiceportal.js:307 2892,70,75 => soundManager.onPosition('sound_0', 2892, function () { setSubtitle(49,54); })
voiceportal.js:313 start play sound_0
voiceportal.js:187 setSubtitle(0, 1) - offset: 0
voiceportal.js:187 setSubtitle(9, 16) - offset: 0
voiceportal.js:187 setSubtitle(2, 8) - offset: 0
voiceportal.js:187 setSubtitle(17, 19) - offset: 0
voiceportal.js:187 setSubtitle(20, 29) - offset: 0
voiceportal.js:187 setSubtitle(30, 35) - offset: 0
voiceportal.js:187 setSubtitle(39, 46) - offset: 0
voiceportal.js:187 setSubtitle(36, 38) - offset: 0
voiceportal.js:187 setSubtitle(49, 54) - offset: 0
voiceportal.js:187 setSubtitle(47, 48) - offset: 0


What happens is that in two cases the callbacks from soundmanager2 comes in the wrong order:
1) setSubtitle(2, 8) is called after setSubtitle(9, 16)
2) setSubtitle(36, 38) is called after setSubtitle(39, 46)

This is consistent, we get the same sequencing error everytime we play the same sentence.

Even more weird, the error seems to be the same independently on the speed of the speech.

**Comment by izaxon** [comment]
> html5PollingInterval
> Setting this will enable a single interval that will affect the frequency of event callbacks such whileplaying() for HTML5 sounds, with the exclusion of mobile devices. If null, native HTML5 update events are used. The frequency of native events may vary widely across browsers, and may exceed 500 msec on mobile and other resource-limited devices.
> By default, Flash uses a 50-msec timer interval and this is a reasonable value to apply to html5PollingInterval for desktop use cases.

http://www.schillmania.com/projects/soundmanager2/doc/#sm-config

**Comment by PaoloLeva** [comment]
Fixed on website, sent to our friends on faroer for tests
