### ISSUE TITLE
External login (Google) - maybe unique bug?

### ISSUE THREAD

**Issue by Bjartensen** [accelerande/teldutala.fo#2]
I wrote on the bugdb, but the issue is separate from that particular bug I guess. I setup some recording software, so that I can record it and show what bugs look like. This happens when I log in with Google, but after some testing it seems to only happen with one account, which may again be related to it being one of the first accounts. [video](https://drive.google.com/file/d/0B-V5WEx_UAYiMXZPM19POVBzQkk/view?usp=sharing)

**Comment by accelerande** [comment]
I looked at the video. I think the reason for the error message is that you are already previously registered as a user with a local account at the site. Therefore you cannot register the Google account which has the same email address as the local account.
