### ISSUE TITLE
Word import not working

### ISSUE THREAD

**Issue by izaxon** [accelerande/teldutala.fo#3]
File is processed correctly but job/file state is not updated properly.

**Comment by izaxon** [comment]
@PaoloLeva bug fixed now?

**Comment by PaoloLeva** [comment]
inte än, Word Importer fungerar nu för voiceportalweb.azurewebsites.net men inte för teldutala.fo

**Comment by PaoloLeva** [comment]
Bug is now fixed. Bjartur please verify.

**Comment by Bjartensen** [comment]
@PaoloLeva @izaxon it works.
