### ISSUE TITLE
Error when logging in with facebook

### ISSUE THREAD

**Issue by PaoloLeva** [accelerande/teldutala.fo#35]
When using the Facebook button the following error is displayed:

> Warning
> Kan inte ladda URL: Domänen för denna URL är inte inkluderad i appens domäner. Ladda URL:en genom att ange appens samtliga domäner och underdomäner i fältet Appdomäner i appinställningarna.

Probably connected to #34

**Comment by PaoloLeva** [comment]
Facebook inloggning fixed.

**Comment by mikaelsterley** [comment]
Hi PaoloLeva,
How did you fix the problem?
