### ISSUE TITLE
design issues

### ISSUE THREAD

**Issue by PaoloLeva** [accelerande/teldutala.fo#4]
I just now noticed it, but "Høvundur" (author of the documents you have opened) seems too close to the box, and is actually colliding. Also, the title and description in the Bug Report box has too similar color to the background. The Bug Report box could have the same background color as the website to fix this.

**Comment by PaoloLeva** [comment]
fixed, Bjartur could you verify (and close the issue if OK)?

**Comment by PaoloLeva** [comment]
Fixed font color for BugReport

**Comment by Bjartensen** [comment]
Yes, seems fixed now.

Closing the issue.
